### ISSUE TITLE
Should I implement EPRT and PORT at the same time? Does the username matter in anonymous login?

### ISSUE THREAD

**Issue by Estraie** [dazhi0619/CS305-23S-Assignment1#1]
Do I need to implement EPRT command in my FTP server? (Is that compulsory?)

**Comment by wyatt-feng** [comment]
You can choose either one between PORT and EPRT commands. That being said, it is recommended to choose EPRT since it’s modern and easier to implement.

**Comment by Estraie** [comment]
How does the anonymous login work? Could any random username be accepted under the anonymous mode?

**Comment by wyatt-feng** [comment]
Anonymous login should only take "anonymous" as the username, but you don't have to check it for Task 1. However, if you implement user login control described in "Other Tasks", you should make sure that only "anonymous" can be used to login anonymously.

By the way, when raising issues on GitHub, you should think of a descriptive title. And if you have another question, you should open another issue. This helps others.

**Comment by wyatt-feng** [comment]
I'm going to reopen this issue so others can easily find out. Do not comment down below if your question/comment is irrelevant.
