### ISSUE TITLE
Fail all the test

### ISSUE THREAD

**Issue by TsingYiPainter** [dazhi0619/CS305-23S-Assignment1#12]
I've implemented a simple demo so far and do some simple test on my PC. It looks like it can work.
![((4~WC7GG3)3DEGC$)E%EPI](https://user-images.githubusercontent.com/83380147/227704858-87a6eaac-c4e4-4611-b66d-a95f826ce6c5.png)
![9NV6 ZZU5%Q560~OHG@KV2B](https://user-images.githubusercontent.com/83380147/227704867-62896902-e657-4246-9bd8-299f4e86cff9.png)
In the first photo, it show the command that server recive, and the second photo is the response

My environment is WSL,IDEA is Pycharm, python version is 3.9.1

But I fail all the test, and I don't know why. Actually, I don't know how to respond to the `TYPE I` command and I just response "200 Type set to: Binary."

I am a newbie in Network and hope to get your help.

**Comment by wyatt-feng** [comment]
I would advise that you use `ftp` to test your server, capture the packets during test, compare the result with the packets provided. Maybe you need to read the document more carefully for the details like the trailing `\r\n` and how data connections work.

As for the `TYPE I` part, I believe that you are doing it right.

A kind reminder: You do need to pick up your pace at this point of time.

**Comment by Teng-Pan** [comment]
I meet the same problem as yours, I guess your problem is probably that you don't send '221 Goodbye.' if the client send 'QUIT'.

**Comment by TsingYiPainter** [comment]
Thank you, this is due to my negligence

**Comment by TsingYiPainter** [comment]
I have a new problem.
![QE3IP~FG8G(`NA}%7AT G1E](https://user-images.githubusercontent.com/83380147/227765524-dc534c38-d02b-4930-ab2a-13a1ef37bd8e.png)

When I testing, The program will jam at this step.
I found that testing script sends two consecutive blank data packets after I use `Ctrl+C` to stop the program.
I learned that accepting two blank packets in a row should be reported to the SA. I'm not sure if it's the same thing as my problem.

**Comment by wyatt-feng** [comment]
Let me clarify the situation first. Did you use `Ctrl+C` to terminate the testing script during its test? This sounds weird because normally you do not need to manually stop the testing script.

**Comment by TsingYiPainter** [comment]
It's okay now. It's because I didn't process the message properly. Thank you!

**Comment by TsingYiPainter** [comment]
I have a problem that I haven't solved for a long time. I can no longer run the test program on the Windows system because I don't have enough permissions. SA said that maybe the port 52305 was retained by some software registration on my computer. For details, you can see my discussion in the qq group on 3.26 evening.

However, it is very troublesome to catch the package on wsl. I tried, but there was no result.

At present, I can pass all the tests, but it is expected that my report cannot contain the screenshot of package capture. May I ask what I should do?

**Comment by TsingYiPainter** [comment]
Well, after changing the port, my problem was solved and completed this assignment, thanks to all the people who helped me.
