### ISSUE TITLE
tcp port number reused

### ISSUE THREAD

**Issue by qwq-y** [dazhi0619/CS305-23S-Assignment1#15]
![image](https://user-images.githubusercontent.com/94696811/227848605-b70fcc0a-a3ce-424d-a733-2774cec27908.png)
![image](https://user-images.githubusercontent.com/94696811/227848706-75e1b1f7-06b6-40d6-9cf8-07a6521a0f36.png)
![image](https://user-images.githubusercontent.com/94696811/227848754-9ab247cf-cc8f-43d9-a516-19b074dc5421.png)
如图一，Wireshark 抓的包中，前几个会报错。但是我在代码中写了检查是否被占用的函数，并且没有得到被占用的输出。请问这是为什么，该如何解决呀？

**Comment by wyatt-feng** [comment]
I have not encountered this ever so I am not quite sure why. My speculation is that the way you are using Python socket library causes this problem. Do you use `accept()` after `listen()`?

**Comment by qwq-y** [comment]
yes, accept() in a while true loop, after listen()

**Comment by wyatt-feng** [comment]
If you believe it is because the 52305 port is not available for any reason, you can contact me on QQ and I will send you a customized testing script that use another port.
