### ISSUE TITLE
command errors fail

### ISSUE THREAD

**Issue by AlbertZhang2333** [dazhi0619/CS305-23S-Assignment1#16]
![image](https://user-images.githubusercontent.com/100056293/228123317-bee4869e-8a02-4a36-a5e1-c5429d683ab7.png)
I have tried all the return code but still fail the command errors. The code of this part is same as others, just send the return code and receive next comment. Does the requirements of command errors have difference with  file errors and connection errors?

**Comment by wyatt-feng** [comment]
What are the status codes for these tests?

**Comment by AlbertZhang2333** [comment]
I have tried 430 501 502 504 530 for testcase of command error

**Comment by wyatt-feng** [comment]
Can you show me the packets during the command error test of your server?

**Comment by AlbertZhang2333** [comment]
Oh thank you I have fixed it. it is because my status code in responce to another request is wrong.
