### ISSUE TITLE
Commands that are defined as valid in this assignment.

### ISSUE THREAD

**Issue by ghost** [dazhi0619/CS305-23S-Assignment1#17]
After trying to implement the invalid command handling part, I wonder if there is any command other than {
QUIT
TYPE
USER
PASS
PORT
EPRT
STOR
RETR
SIZE
SYST
FEAT
MDTM
} that is be defined as valid in this Assignment.

Much appreciate to your work.

**Comment by wyatt-feng** [comment]
In this assignment, we will only verify if your server can handle USER PASS PORT/EPRT STOR RETR QUIT. No other commands will be tested.
