### ISSUE TITLE
Unexpected \r\nQUIT in non-error-handling part.

### ISSUE THREAD

**Issue by ghost** [dazhi0619/CS305-23S-Assignment1#18]
![Screenshot 2023-03-28 142732](https://user-images.githubusercontent.com/61125620/228148585-f8b35c1f-ab3e-414f-8db6-a27f335f8681.png)
Seems like there is a request having 'QUIT' after \r\n in the first part -> file transfer section.

**Comment by wyatt-feng** [comment]
I'm pretty sure it is because your server cannot correctly handle `\r\n`
