### ISSUE TITLE
macOS cannot recognize "TYPE I"

### ISSUE THREAD

**Issue by yuyuliu11037** [dazhi0619/CS305-23S-Assignment1#19]
To set the file transfer mode to binary (TYPE I) in macOS Terminal, I have to type "binary" instead of "TYPE I", because the latter one is not recognizable. Therefore, my program cannot correctly receive the "TYPE I" command from the test script.

I've tried many ways, but it seems that I cannot make my machine to recognize "TYPE I".
<img width="549" alt="截屏2023-03-29 00 32 16" src="https://user-images.githubusercontent.com/100055995/228307637-eb269584-c9ed-4985-b244-a491491ef396.png">

**Comment by wyatt-feng** [comment]
Your question is essentially the same as #9. Read through the document and the issues when facing a problem and before asking, please.

**Comment by yuyuliu11037** [comment]
I ignored the closed issues. Thanks.
