### ISSUE TITLE
Should all packets captured in Wireshark be included in the screenshot？

### ISSUE THREAD

**Issue by Cooperzzy** [dazhi0619/CS305-23S-Assignment1#6]
There are about 250 packets captured during the process. And all packets are like 
54383 → 52305 [PSH, ACK] Seq=59 Ack=130 Win=408128 Len=20 TSval=1613228748 TSecr=1356324646. Is this OK?

**Comment by wyatt-feng** [comment]
Yes for the screenshot and no for the packet format, you should include the screenshot of them after you set the filters correctly. I will update the document to tell you how.

**Comment by Cooperzzy** [comment]
Thanks. After setting the decoding format and display filter as 'tcp.port == 52305', the packets are basically listed as one TCP line, followed by a FTP line line by line. Should I modify the filter as 'ftp' to display ftp info only or just use 'tcp.port==52305' ?

**Comment by wyatt-feng** [comment]
Yes, it will be great if you can do so.
