### ISSUE TITLE
Encounter the problem ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by kozoy** [dazhi0619/CS305-23S-Assignment1#7]
When I run the test script, this error occurs.

**Comment by wyatt-feng** [comment]
Excerpt from the document, section “Usage of the testing script”:

> Rename your server code to be server.py and **run it**, then use the following command to run the testing script[…]

You have to run your server before you execute the testing script.

**Comment by kozoy** [comment]
I followed the document. But still failed.

**Comment by wyatt-feng** [comment]
Can you check if your server listens on port 52305? And if you are running your server inside WSL, you may as well try running the testing script inside it.

**Comment by kozoy** [comment]
Yes, when I run telnet 127.0.0.1 52305, it will connect correctly.

**Comment by wyatt-feng** [comment]
Does the `ftp` command work find with your server?

**Comment by kozoy** [comment]
Yes, I opened ftp server and it can work. But I closed it because the port will be occupied.

**Comment by kozoy** [comment]
I solved this problem by accident. I don't know how and why. But it works now.

**Comment by wyatt-feng** [comment]
Sometimes it happens. For those who come across the same problem, I suggest you go through the above comments and try restarting your server or even your computer.

**Comment by qwq-y** [comment]
I encountered the same problem, I can pass the USER command, but for EPRT, it comes to "由于目标计算机积极拒绝，无法连接". I have turned off the firewall, and tried restart, but it still not work.

**Comment by wyatt-feng** [comment]
> I encountered the same problem, I can pass the USER command, but for EPRT, it comes to "由于目标计算机积极拒绝，无法连接". I have turned off the firewall, and tried restart, but it still not work.

Can you be more specific? What is your environment?

**Comment by qwq-y** [comment]
I run in Windows, anaconda, python 3.9.16, with or without VPN. I think that ftp commands could work because USER passed.

**Comment by Kazawaryu** [comment]
Same error, even I've made all ports public and close firewall, tried restarting my server and my computer.

**Comment by wyatt-feng** [comment]
Can you both find out the connection to which port leads to this error? I presume it is because the way you parse `EPRT` or `PORT` is wrong.

**Comment by Kazawaryu** [comment]
> 

You're right, I thought it is satisfied only implementing one of the two functions, thx🙏
