### ISSUE TITLE
When I run PORT 127,0,0,1,135,7 in ftp, it returns Invalid command and can't go into my PORT logic

### ISSUE THREAD

**Issue by hehan2** [dazhi0619/CS305-23S-Assignment1#9]
EPRT is the same

**Comment by wyatt-feng** [comment]
As far as I know, there is no way to directly use ftp to send PORT command. If you wish to do so, you have to use `ftplib` that is shipped with python standard library. Moreover, you have to keep it in mind that `ftp` command is a FTP client, so its commands are not the same as the commands defined in the FTP protocol. If you need help with the usage of `ftp`, you should refer to the manual. For example, on linux, execute `man ftp`.
